AWSTemplateFormatVersion: '2010-09-09'
Description: This stack deploys the resources needed to create a static website

###############################################################################
# Parameters
###############################################################################

Parameters:
  Environment:
    Description: Environemnt type
    Type: String
    AllowedValues:
      - production
      - staging
      - development
    ConstraintDescription: Must specify production, staging, or development
    Default: development
  BranchName:
    Description: The git branch that defines this deploy
    Type: String
    Default: master
  AppName:
    Description: subdomain wording that will identify this static web
    Type: String
    Default: app
  DomainName:
    Description: Your domain name
    Type: String
  AcmCertificateArn:
    Description: ARN of the SSL certificate to serve. Currently onle us-east-1 is supported
    Type: String

###############################################################################
# Conditions
###############################################################################

Conditions:
  IsProd: !Equals
    - !Ref Environment
    - 'production'

###############################################################################
# Resources
###############################################################################

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        !Sub '${BranchName}.${Environment}.${DomainName}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: [ '*' ]
            AllowedMethods: [ GET ]
            AllowedOrigins:
              - !If
                - IsProd
                # Short CNAME for prod only
                - !Sub '${AppName}.${DomainName}'
                # Autogenerated CNAME
                - !Sub '${BranchName}_${Environment}_${AppName}.${DomainName}'
            ExposedHeaders: [ Date ]
            Id:
              !Sub '${BranchName}-${Environment}'
            MaxAge: '3600'
      Tags:
        -
          Key: Name
          Value:
            !Sub '${Environment}-${BranchName}-S3Bucket'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: !Sub '${BranchName}-${Environment}'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !If
            - IsProd
            - !Sub '${AppName}.${DomainName}'
            - !Sub '${BranchName}-${Environment}.${DomainName}'
        CacheBehaviors:
          -
            TargetOriginId:
              !Sub 'S3-${BranchName}.${Environment}.${DomainName}'
            PathPattern: '*'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            DefaultTTL: 3600
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: false
            MaxTTL: 86400
            MinTTL: 60
            SmoothStreaming: false
            ViewerProtocolPolicy: 'redirect-to-https'
        DefaultCacheBehavior:
          TargetOriginId:
            !Sub 'S3-${BranchName}.${Environment}.${DomainName}'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400
          MinTTL: 60
          SmoothStreaming: false
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http2'
        IPV6Enabled: true
        Origins:
          -
            DomainName: !Sub '${BranchName}.${Environment}.${DomainName}.s3.amazonaws.com'
            Id: !Sub 'S3-${BranchName}.${Environment}.${DomainName}'
            S3OriginConfig:
              OriginAccessIdentity: ''
        PriceClass: 'PriceClass_100'
        ViewerCertificate:
          AcmCertificateArn:
            !Ref AcmCertificateArn
          MinimumProtocolVersion: 'TLSv1'
          SslSupportMethod: 'sni-only'
      Tags:
        -
          Key: Name
          Value:
            !Sub '${Environment}-${BranchName}-CloudFront'

###############################################################################
# Outputs
###############################################################################

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3

  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content